### ISSUE TITLE
Library installation

### ISSUE THREAD

**Issue by BY-hash** [dss-extensions/dss_python#37]
Hi,
When installing only dss_python I get an error 
AttributeError: module 'dss' has no attribute 'DSS'

However,when installing also 'dss', the code works.
( I get the same error when installing only 'dss')

In your documentations it seems that one only needs to install dss_python.
Is there really a dependency on 'dss' library?
Why is this happening?

Thank you!

**Comment by PMeira** [comment]
No, the dss module on PyPI is completely unrelated (and seems to be dead), nothing to do with OpenDSS at all. Please uninstall that (in fact, it's probably better to uninstall/reinstall DSS Python too after that).

The only hard dependencies are CFFI and NumPy, which should be installed automatically if required, but usually are already installed for most users.

> Why is this happening?

Without details on your installation environment (OS, processor architecture, Python version, etc.), not much we could say.

One common thing seen in Python happens when users have a conflicting module, e.g. if you have a file named `dss.py` or a `dss` folder/package in your Python path, that could be shadowing the installed package.
