### ISSUE TITLE
About traversing the elements to find power sources

### ISSUE THREAD

**Issue by mauricioborges** [dss-extensions/dss_python#39]
Hello there,

First of all, thanks for your awesome work here!

I'm working with dss_python trying to turn off loads across the circuit to see its impact across different elements. I'd like to know if there's a way to traverse the element tree in order to find what are the possible sources for that specific load, i.e.:
```
transformer1 -> line1 -> line2 -> load1
```
I'd like to "find out" that load1 is powered by transformer1, even though it's not direct.

I could walk through the graph and find it's relationships by myself and I believe dss_capi doesn't do that, but I decided to ask before writing an algorithm that does that.

obs: I'm from software engineering background so maybe my question doesn't make any sense. Thanks!

**Comment by PMeira** [comment]
Closing since this was addressed in the forum (that explains the lack of response here sooner). Ref: https://sourceforge.net/p/electricdss/discussion/861977/thread/bba9580535/

To complement for future reference, for basic usage the internal features of the EnergyMeter (and the `DSS.ActiveCircuit.Topology` API) should be enough. For repeated/performance sensitive situations, it would be better to extract the the graph and process it according to your needs. At Unicamp, we extract the whole matrix and process it in C++ in some situations, for example. In other scenarios where the data is converted "just-in-time" for OpenDSS, we process the original graph before the conversion to DSS scripts.

As we've been doing for the rest of the OpenDSS features, there are plans to rewrite and extend the graph processing in DSS C-API, but that's a post v2.0 goals (i.e. not targeted for a few months, but should be done still in 2022).
